apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pdf-tracker-backend-data
  labels:
    app: pdf-tracker
    component: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: snap
